  
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'
trigger:
- master

steps:

- task: DownloadSecureFile@1
  name: github_docker
  inputs:
    secureFile: 'github-docker.txt'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cat $(github_docker.secureFilePath)| docker login docker.pkg.github.com -u bryht --password-stdin
      npm install
      npm run build
  displayName: 'Build file'

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: docker.pkg.github.com/bryht/video-chat-game/video-chat-game:latest
    command: build
    Dockerfile: ./Dockerfile