  
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'
trigger:
- master

steps:

- task: DownloadSecureFile@1
  name: github_docker
  inputs:
    secureFile: 'github-docker.txt'

- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: PowerShell@2
  displayName: Docker login
  inputs:
    targetType: 'inline'
    script: |
      cat $(github_docker.secureFilePath)| docker login docker.pkg.github.com -u bryht --password-stdin

- task: Docker@2
  displayName: Docker build
  inputs:
    repository: docker.pkg.github.com/bryht/video-chat-game/video-chat-game:latest
    command: build
    Dockerfile: ./Dockerfile

- task: PowerShell@2
  displayName: Docker Push
  inputs:
    targetType: 'inline'
    script: |
      docker push docker.pkg.github.com/bryht/video-chat-game/video-chat-game:latest